Repository SOPT-all/36-STUDY-SERVER-TESTCODE, pull requests merged in 2025-06, with the labels that each got.

#67 3주차 실습
  src/main/java/sopt/study/testcode/geunpyo/config/EnableJpaAuditingConfig.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/order/OrderController.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/product/ProductController.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/product/response/ProductResponse.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/order/response/OrderResponse.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/BaseEntity.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/order/Order.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/order/OrderRepository.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/order/OrderStatus.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/orderproduct/OrderProduct.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/orderproduct/OrderProductRepository.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/Product.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductSellingStatus.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKiosk.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/geunpyo/unit/order/Order.java
  src/test/java/sopt/study/testcode/geunpyo/spring/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/geunpyo/spring/domain/order/OrderTest.java
  src/test/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductRepositoryTest.java
  src/test/java/sopt/study/testcode/geunpyo/unit/beverage/AmericanoTest.java
  src/test/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKioskTest.java
Labels: 근표

#90 4주차 실습
  src/main/java/sopt/study/testcode/kyongmin/spring/CafeKioskApplication.java
  src/main/java/sopt/study/testcode/kyongmin/spring/config/JpaAuditingConfig.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/ApiControllerAdvice.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/ApiResponse.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/OrderController.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/product/ProductController.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/product/dto/request/ProductCreateRequest.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/product/request/ProductCreateServiceRequest.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/stock/Stock.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/stock/StockRepository.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/OrderControllerTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/product/ProductControllerTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/api/service/product/ProductServiceTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductRepositoryTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductTypeTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/stock/StockRepositoryTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/stock/StockTest.java
Labels: 경민

#89 4주차 실습
  http/order.http
  src/main/java/sopt/study/testcode/TestcodeApplication.java
  src/main/java/sopt/study/testcode/seongjae/api/ApiControllerAdvice.java
  src/main/java/sopt/study/testcode/seongjae/api/ApiResponse.java
  src/main/java/sopt/study/testcode/seongjae/api/controller/order/OrderController.java
  src/main/java/sopt/study/testcode/seongjae/api/controller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/seongjae/api/controller/product/ProductController.java
  src/main/java/sopt/study/testcode/seongjae/api/controller/product/dto/request/ProductCreateRequest.java
  src/main/java/sopt/study/testcode/seongjae/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/seongjae/api/service/order/request/OrderCreateServiceRequest.java
  src/main/java/sopt/study/testcode/seongjae/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/seongjae/api/service/product/request/ProductServiceCreateRequest.java
  src/main/java/sopt/study/testcode/seongjae/config/JpaAuditingConfig.java
  src/main/java/sopt/study/testcode/seongjae/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/seongjae/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/seongjae/domain/stock/Stock.java
  src/main/java/sopt/study/testcode/seongjae/domain/stock/StockRepository.java
  src/main/java/sopt/study/testcode/seongjae/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/seongjae/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/seongjae/unit/order/Order.java
  src/test/java/sopt/study/testcode/seongjae/api/controller/order/OrderControllerTest.java
  src/test/java/sopt/study/testcode/seongjae/api/controller/product/ProductControllerTest.java
  src/test/java/sopt/study/testcode/seongjae/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/seongjae/api/service/product/ProductServiceTest.java
  src/test/java/sopt/study/testcode/seongjae/domain/product/ProductRepositoryTest.java
  src/test/java/sopt/study/testcode/seongjae/domain/product/ProductTypeTest.java
  src/test/java/sopt/study/testcode/seongjae/domain/stock/StockRepositoryTest.java
  src/test/java/sopt/study/testcode/seongjae/domain/stock/StockTest.java
  src/test/java/sopt/study/testcode/seongjae/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/seongjae/unit/beverage/AmericanoTest.java
Labels: 성재

#99 5주차 실습
  src/main/java/sopt/study/testcode/geunpyo/spring/api/ApiControllerAdvice.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/ApiResponse.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/order/OrderController.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/product/ProductController.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/controller/product/request/ProductCreateRequest.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/order/request/OrderCreateServiceRequest.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/product/request/ProductCreateServiceRequest.java
  src/main/java/sopt/study/testcode/geunpyo/spring/api/service/product/response/ProductResponse.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/stock/Stock.java
  src/main/java/sopt/study/testcode/geunpyo/spring/domain/stock/StockRepository.java
  src/test/java/sopt/study/testcode/geunpyo/spring/api/controller/order/OrderControllerTest.java
  src/test/java/sopt/study/testcode/geunpyo/spring/api/controller/product/ProductControllerTest.java
  src/test/java/sopt/study/testcode/geunpyo/spring/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/geunpyo/spring/api/service/product/ProductServiceTest.java
Labels: 근표
