Repository SOPT-all/36-STUDY-SERVER-TESTCODE, pull requests merged in 2025-05, with the labels that each got.

#4 1주차 실습
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKiosk.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/geunpyo/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/geunpyo/unit/order/Order.java
  src/test/java/sopt/study/testcode/geunpyo/unit/beverage/AmericanoTest.java
  src/test/java/sopt/study/testcode/geunpyo/unit/beverage/CafeKioskTest.java
Labels: 근표

#9 1주차 실습
  build.gradle
  src/main/java/sopt/study/testcode/spring/TestcodeApplication.java
  src/main/java/sopt/study/testcode/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/unit/order/Order.java
  src/test/java/sopt/study/testcode/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/unit/beverage/AmericanoTest.java
Labels: 민혁

#13 1주차 실습
  build.gradle
  src/main/java/sopt/study/testcode/yeongju/spring/TestCodeStuduyApplication.java
  src/main/java/sopt/study/testcode/yeongju/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/yeongju/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/yeongju/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/yeongju/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/yeongju/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/yeongju/unit/order/Order.java
  src/test/java/sopt/study/testcode/yeongju/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/yeongju/unit/beverage/AmericanoTest.java
Labels: 영주

#11 1주차 실습
  src/main/java/sopt/study/testcode/soyeon/TestcodeApplication.java
  src/main/java/sopt/study/testcode/soyeon/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/soyeon/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/soyeon/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/soyeon/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/soyeon/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/soyeon/unit/order/Order.java
  src/test/java/sopt/study/testcode/soyeon/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/soyeon/unit/beverage/AmericanoTest.java
Labels: 소연

#17 1주차 실습
  src/main/java/sopt/study/testcode/sangbeom/spring/CafekioskApplication.java
  src/main/java/sopt/study/testcode/sangbeom/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/sangbeom/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/sangbeom/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/sangbeom/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/sangbeom/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/sangbeom/unit/order/Order.java
  src/test/java/sopt/study/testcode/sangbeom/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/sangbeom/unit/beverage/AmericanoTest.java
Labels: 상범

#19 1주차 실습
  src/main/java/sopt/study/testcode/kyongmin/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/kyongmin/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/kyongmin/unit/order/Order.java
  src/test/java/sopt/study/testcode/kyongmin/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/kyongmin/unit/beverage/AmericanoTest.java
Labels: 경민

#21 1주차 실습
  src/main/java/sopt/study/testcode/hyunjin/unit/Beverage.java
  src/main/java/sopt/study/testcode/hyunjin/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/hyunjin/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/hyunjin/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/hyunjin/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/hyunjin/unit/common/ResponseError.java
  src/main/java/sopt/study/testcode/hyunjin/unit/order/Order.java
  src/test/java/sopt/study/testcode/hyunjin/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/hyunjin/unit/beverage/AmericanoTest.java
Labels: 현진

#27 feat : 1주차 실습
  src/main/java/sopt/study/testcode/yerin/Americano.java
  src/main/java/sopt/study/testcode/yerin/Beverage.java
  src/main/java/sopt/study/testcode/yerin/CafeKiosk.java
  src/main/java/sopt/study/testcode/yerin/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/yerin/Latte.java
  src/main/java/sopt/study/testcode/yerin/Order.java
  src/test/java/sopt/study/testcode/yerin/AmericanoTest.java
  src/test/java/sopt/study/testcode/yerin/CafeKioskTest.java
Labels: 예린

#28 [week1] 1주차 과제
  src/test/java/sopt/study/testcode/jaemin/TestCode.java
Labels: 재민

#31 1주차 실습
  src/main/java/sopt/study/testcode/chaeryun/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/chaeryun/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/chaeryun/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/chaeryun/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/chaeryun/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/chaeryun/unit/order/Order.java
  src/test/java/sopt/study/testcode/chaeryun/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/chaeryun/unit/beverage/AmericanoTest.java
Labels: 채륜

#35 1주차 실습
  src/main/java/sopt/study/testcode/seongjae/README.md
  src/main/java/sopt/study/testcode/seongjae/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/seongjae/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/seongjae/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/seongjae/unit/order/Order.java
  src/test/java/sopt/study/testcode/TestcodeApplicationTests.java
  src/test/java/sopt/study/testcode/seongjae/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/seongjae/unit/beverage/AmericanoTest.java
Labels: 성재

#69 3주차 실습
  src/main/java/sopt/study/testcode/kyongmin/spring/CafeKioskApplication.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/BaseEntity.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/OrderController.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/order/response/OrderResponse.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/contoller/product/ProductController.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/api/service/product/response/ProductResponse.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/order/Order.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/order/OrderRepository.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/order/OrderStatus.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/orderproduct/OrderProduct.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/orderproduct/OrderProductRepository.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/Product.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductSellingStatus.java
  src/main/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/kyongmin/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/kyongmin/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/kyongmin/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/kyongmin/unit/order/Order.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/order/OrderTest.java
  src/test/java/sopt/study/testcode/kyongmin/spring/domain/product/ProductRepositoryTest.java
  src/test/java/sopt/study/testcode/kyongmin/unit/CafeKioskTest.java
  src/test/java/sopt/study/testcode/kyongmin/unit/beverage/AmericanoTest.java
Labels: 경민

#91 3주차 실습
  README.md
  build.gradle
  http/order.http
  http/product.http
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/CafeKioskApplication.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/controller/order/OrderController.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/controller/order/request/OrderCreateRequest.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/controller/product/ProductController.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/service/order/OrderService.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/service/order/response/OrderResponse.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/service/product/ProductService.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/api/service/product/response/ProductResponse.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/BaseEntity.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/order/Order.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/order/OrderRepository.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/order/OrderStatus.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/orderproduct/OrderProduct.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/product/Product.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/product/ProductRepository.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/product/ProductSellingStatus.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/product/ProductType.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/CafeKiosk.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/CafeKioskRunner.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/beverage/Americano.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/beverage/Beverage.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/beverage/Latte.java
  src/main/java/sopt/study/testcode/hyeeum/cafekiosk/unit/order/Order.java
  src/main/resources/data.sql
  src/test/java/sopt/study/testcode/cafekiosk/CafeKioskApplicationTests.java
  src/test/java/sopt/study/testcode/cafekiosk/spring/api/service/order/OrderProductRepository.java
  src/test/java/sopt/study/testcode/cafekiosk/spring/api/service/order/OrderServiceTest.java
  src/test/java/sopt/study/testcode/cafekiosk/spring/domain/product/ProductRepositoryTest.java
  src/test/java/sopt/study/testcode/hyeeum/cafekiosk/spring/domain/order/OrderTest.java
  src/test/java/sopt/study/testcode/unit/beverage/AmericanoTest.java
  src/test/java/sopt/study/testcode/unit/beverage/CafeKioskTest.java
Labels: 혜음
